### ISSUE TITLE
UNA VDC Server Packages

### ISSUE THREAD

**Issue by MerseyHostingHub-BM** [MerseyHostingHub/Website#10]
New UNA VDC Server Packages.

Packages will start with the following features from approx £140

2 CPU
120GB Diskspace
8192MB Memory
10000GB Bandwidth
UNA Pro License (Priced @ $50)
DirectAdmin Control Panel - 10 Domain Limit
Cloud Linux for performance and security.
Free Server Management
Free UNA Management
Free UNA App Management (App Licence Purchase Required via our Client Panel)
Optional RocketChat Server Addon
Optional HTML5 Chat Addon (Free & Paid Versions)

### Task List

- [x] Setup of Packages on our website.
- [x] Setup of Packages in Client Panel.
- [x] Setup of RocketChat Server Addon.
- [x] Setup of HMTL5 Chat Addon.
- [x] Setup of App Addon.

**Comment by MerseyHostingHub-BM** [comment]
Confirmation of;

- Package Names
- Package Resources

![screenshot-www merseyhostinghub co uk-2021 01 15-20-38-08](https://user-images.githubusercontent.com/75571890/104776370-e5028280-5771-11eb-94dc-2561254a0926.png)

**Comment by MerseyHostingHub-BM** [comment]
We have decided that we are going to provide a free and paid version of HTML5 Chat. Both with a free integration with our mod.

**Comment by MerseyHostingHub-BM** [comment]
Full Package Confirmation for this release.
![UNA VDC Packages](https://user-images.githubusercontent.com/75571890/105535204-7c258800-5ce6-11eb-8967-b700dfef7e9f.png)

**Comment by MerseyHostingHub-BM** [comment]
Completed
